version: "3.8"

services:
  app:
    container_name: vietentertainment-viet-cms
    image: vietentertainment2023/cms:latest
    environment:
      - REACT_APP_API=${REACT_APP_API}
      - REACT_APP_MOCK_API=${REACT_APP_MOCK_API}
      - REACT_APP_ENV=${REACT_APP_ENV}
      - REACT_KEYCLOAK_API=${REACT_KEYCLOAK_API}
    ports:
      - "3005:80"
    restart: unless-stopped