export const CREATE_ACHIEVEMENT = 'App/MyApp/CREATE_ACHIEVEMENT';
export const LOAD_ACHIEVEMENT = 'App/MyApp/LOAD_ACHIEVEMENT';
export const LOAD_ACHIEVEMENT_SUCCESS = 'App/MyApp/LOAD_ACHIEVEMENT_SUCCESS';
export const LOAD_ACHIEVEMENT_ERROR = 'App/MyApp/LOAD_ACHIEVEMENT_ERROR';
