export const talentRole = 'TALENT_READ_ACCESS';
export const orgRole = 'ORGANIZER_READ_ACCESS';
export const adminRole = [
  'ADMIN_READ_ORGANIZER_ACCESS',
  'ADMIN_RESOLVE_ORGANIZER_ACCESSS',
  'ADMIN_ARCHIVE_ORGANIZER_ACCESS',
  'ADMIN_READ_TALENT_ACCESS',
  'ADMIN_RESOLVE_TALENT_ACCESS',
  'ADMIN_ARCHIVE_TALENT_ACCESS',
];
