export const bdRole = [
  'ADMIN_READ_TALENT_ACCESS',
  'ADMIN_READ_BOOKING_ACCESS',
  'ADMIN_RESOLVE_BOOKING_ACCESS',
];
export const oaRole = [
  'ADMIN_RESOLVE_TALENT_ACCESS',
  'ADMIN_ARCHIVE_ORGANIZER_ACCESS',
  'ADMIN_READ_ORGANIZER_ACCESS',
  'ADMIN_READ_TALENT_ACCESS',
  'ADMIN_RESOLVE_ORGANIZER_ACCESS',
  'ADMIN_READ_BOOKING_ACCESS',
  'ADMIN_ARCHIVE_TALENT_ACCESS',
];
export const accountantRole = [
  'ADMIN_READ_TALENT_ACCESS',
  'ADMIN_READ_BOOKING_ACCESS',
];
