export const talentRole = [
  'TALENT_READ_ACCESS',
  'TALENT_WRITE_ACCESS',
  'TALENT_MODIFY_ACCESS',
  'TALENT_PAYMENT_ACCESS',
];
export const orgRole = [
  'ORGANIZER_READ_ACCESS',
  'ORGANIZER_WRITE_ACCESS',
  'ORGANIZER_MODIFY_ACCESS',
  'ORGANIZER_PAYMENT_ACCESS',
];
export const adminRole = [
  'ADMIN_READ_ORGANIZER_ACCESS',
  'ADMIN_RESOLVE_ORGANIZER_ACCESSS',
  'ADMIN_ARCHIVE_ORGANIZER_ACCESS',
  'ADMIN_READ_TALENT_ACCESS',
  'ADMIN_RESOLVE_TALENT_ACCESS',
  'ADMIN_ARCHIVE_TALENT_ACCESS',
];
